accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

mulzu771/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('<str:username>/', accounts_views.profile, name='profile'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
]

accounts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class UserInfo(models.Model):
    building_type = models.IntegerField()
    title = models.CharField(max_length=150)
    period = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODELS, on_delete=models.CASCADE)

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Building(models.Model):
    address = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    floor = models.IntegerField()
    type = models.IntegerField()
    typeCode = models.IntegerField()
    user = models.ManyToManyField(settings.AUTH_USER_MODELS,on_delete=models.CASCADE)


class Post(models.Model):
    content=models.TextField()
    image = models.ImageField(blank=True)
    score = models.IntegerField()
    building = models.ForeignKey(Building,on_delete=models.CASCADE)


class Comment(models.Model):
    content = models.TextField()
    post = models.ForeignKey(Post,on_delete=models.CASCADE)

class Tip(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODELS,on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from .models import UserInfo

class UserInfoForm(forms.modelform):
    class Meta:
        model = UserInfo
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model


# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
        return redirect('posts:list')
    else:
        form = UserCreationForm()        
        return render(request, 'accounts/signup.html', {'form': form})
    

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.user)
        return redirect('posts:list')
    else:
        form = AuthenticationForm(request)
        return render(request, 'accounts/login.html', {'form': form})
    

def logout(request):
    auth_logout(request)
    return redirect('posts:list')
    
    
def profile(request, username):
    profile = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/profile.html', {'profile': profile})

posts/views.py
from django.shortcuts import render

# Create your views here.
def list(request):
    return render(request, 'posts/list.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<div class="col-6 offset-3 mt-3">
  <h1 class = my-3>로그인</h1>
  <form method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type=submit class='btn btn-primary'>로그인</button>
  </form>
</div>
  
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
  <div class="col-8 offset-2">
    <h1>회원정보</h1>
    <h2>{{ profile.username }}</h2>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}
<div class="col-8 offset-2 mt-3">
  <h1 class = my-3>회원가입</h1>
  <form method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type=submit class='btn btn-primary'>회원가입</button>
  </form>
</div>
  
{% endblock %}

posts/templates/main/main.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Font Awsome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    
    <title>건물주**771</title>
  </head>
  <body>
      {% include 'nav.html' %}
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <!-- Vue.js 개발용 CDN -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'posts:list' %}">
    <i class="far fa-building"></i>
      MULZU771
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fas fa-user-circle fa-2x"></i>
          </a>
        </li>
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' user.username %}">{{ request.user }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>